version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:8008@mysql:3306/portfolio
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start
      "
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 8008
      MYSQL_DATABASE: portfolio
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
